version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Ameya
      POSTGRES_PASSWORD: Ameya@123
      POSTGRES_DB: Task-Management
    ports:
      - "5432:5432"